[package]
name = 'nft_rental_regular'
version = '1.0.0'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token", rev = "testnet" }
gnft_coin_mintable = {local = "../gnft_coin_mintable"}

[addresses]
deployer = "_"
ghostnft = "_"
